A couple of typos
Mostafa-Samir/Mostafa-Samir.github.io pull request #4
Opened 2020-04-18 18:26 UTC by mavroudisv

2020-04-19 22:06 UTC, Mostafa-Samir requested changes
Thanks @mavroudisv for the fixes. One change (in the below comment) and the PR will be ready to be merged.

2020-04-19 22:06 UTC, Mostafa-Samir commented on _posts/2016-9-26-ml-theory-pt2.md
> + $$\mathbb{P}\left[\sup_{h \in \mathcal{H}}|R(h) - R_\text{emp}(h)| > \epsilon\right] \leq \mathbb{P}\left[\bigcup_{h \in \mathcal{H}} |R(h) - R_\text{emp}(h)| > \epsilon\right]$$
The probability of the whole space having a generalization gap bigger than epsilon _**is**_ the probability of at least one of the hypotheses in the space having such gap. So the equal sign here is correct, the less-than-or-equal appears in the next equation when we bound the probability of the union by the sum of its individual probabilities.

2020-04-21 11:08 UTC, mavroudisv commented
I believe my latest commit fixes the mistake I introduced. Thanks for the neat intro to ML Theory. :)

2020-04-21 12:16 UTC, Mostafa-Samir commented
You're welcome @mavroudisv! Thank you for the typo fix :+1: Merging now.

2020-04-21 12:16 UTC, merged